[project]
name = "py-gear"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "pillow>=11.3.0",
    "pyside6>=6.9.1",
]
